
# Automatically generated by /home/kevin/Documents/cpsc-120-prompt-lab-11/.action/ccsrcutilities.py on 2023-11-17 17:14:11

TOPTARGETS = all clean spotless format lint header test unittest

SUBDIRS = $(wildcard part-?/.)

default all: all

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -f Makefile -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)

