
# Automatically generated by /mnt/cpsc120/cpsc-120-solution-lab-11/.action/ccsrcutilities.py on 2023-11-07 16:22:55

TOPTARGETS = all clean spotless format lint header test unittest

SUBDIRS = $(wildcard part-?/.)

default all: all

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -f Makefile -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)

